-- ============================================================
-- Migration 014: Switch RLS policies from owner_id to team_id (Phase 3)
-- HIGH RISK — wrapped in a single transaction.
-- If anything breaks: run the rollback block at the bottom.
-- owner_id column is NOT dropped here (that is Phase 5 / migration 015).
-- Storage bucket policies are path-based ({user_id}/...) and are left
-- as-is; signed URLs are generated by Server Actions which already
-- verify team membership through app-layer RLS.
-- ============================================================

BEGIN;

-- ============================================================
-- projects
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON projects;

CREATE POLICY "team full access" ON projects
  FOR ALL
  USING (
    team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
  );

-- ============================================================
-- floors
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON floors;

CREATE POLICY "team full access" ON floors
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM projects p
      WHERE p.id = floors.project_id
        AND p.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- locations
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON locations;

CREATE POLICY "team full access" ON locations
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM floors
      JOIN projects ON projects.id = floors.project_id
      WHERE floors.id = locations.floor_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- files  (three ownership paths: location, floor, task)
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON files;

CREATE POLICY "team full access" ON files
  FOR ALL
  USING (
    (
      location_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM locations
        JOIN floors   ON floors.id   = locations.floor_id
        JOIN projects ON projects.id = floors.project_id
        WHERE locations.id = files.location_id
          AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
      )
    ) OR (
      floor_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM floors
        JOIN projects ON projects.id = floors.project_id
        WHERE floors.id = files.floor_id
          AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
      )
    ) OR (
      task_id IS NOT NULL AND
      EXISTS (
        SELECT 1 FROM tasks
        JOIN projects ON projects.id = tasks.project_id
        WHERE tasks.id = files.task_id
          AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
      )
    )
  );

-- ============================================================
-- issues
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON issues;

CREATE POLICY "team full access" ON issues
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM locations
      JOIN floors   ON floors.id   = locations.floor_id
      JOIN projects ON projects.id = floors.project_id
      WHERE locations.id = issues.location_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- inventory_items
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON inventory_items;

CREATE POLICY "team full access" ON inventory_items
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = inventory_items.project_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- inventory_levels
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON inventory_levels;

CREATE POLICY "team full access" ON inventory_levels
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM inventory_items
      JOIN projects ON projects.id = inventory_items.project_id
      WHERE inventory_items.id = inventory_levels.item_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- inventory_movements
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON inventory_movements;

CREATE POLICY "team full access" ON inventory_movements
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM inventory_items
      JOIN projects ON projects.id = inventory_items.project_id
      WHERE inventory_items.id = inventory_movements.item_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- notes
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON notes;

CREATE POLICY "team full access" ON notes
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = notes.project_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

-- ============================================================
-- tasks
-- ============================================================
DROP POLICY IF EXISTS "owner full access" ON tasks;

CREATE POLICY "team full access" ON tasks
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM projects
      WHERE projects.id = tasks.project_id
        AND projects.team_id IN (SELECT team_id FROM get_user_team_ids(auth.uid()))
    )
  );

COMMIT;


-- ============================================================
-- ROLLBACK SCRIPT (save separately — run this if app breaks)
-- Restores all original owner_id-based policies.
-- ============================================================
/*
BEGIN;

DROP POLICY IF EXISTS "team full access" ON projects;
CREATE POLICY "owner full access" ON projects FOR ALL USING (owner_id = auth.uid());

DROP POLICY IF EXISTS "team full access" ON floors;
CREATE POLICY "owner full access" ON floors FOR ALL USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = floors.project_id AND projects.owner_id = auth.uid())
);

DROP POLICY IF EXISTS "team full access" ON locations;
CREATE POLICY "owner full access" ON locations FOR ALL USING (
  EXISTS (
    SELECT 1 FROM floors JOIN projects ON projects.id = floors.project_id
    WHERE floors.id = locations.floor_id AND projects.owner_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "team full access" ON files;
CREATE POLICY "owner full access" ON files FOR ALL USING (
  (location_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM locations JOIN floors ON floors.id = locations.floor_id
    JOIN projects ON projects.id = floors.project_id
    WHERE locations.id = files.location_id AND projects.owner_id = auth.uid()
  )) OR
  (floor_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM floors JOIN projects ON projects.id = floors.project_id
    WHERE floors.id = files.floor_id AND projects.owner_id = auth.uid()
  )) OR
  (task_id IS NOT NULL AND EXISTS (
    SELECT 1 FROM tasks JOIN projects ON projects.id = tasks.project_id
    WHERE tasks.id = files.task_id AND projects.owner_id = auth.uid()
  ))
);

DROP POLICY IF EXISTS "team full access" ON issues;
CREATE POLICY "owner full access" ON issues FOR ALL USING (
  EXISTS (
    SELECT 1 FROM locations JOIN floors ON floors.id = locations.floor_id
    JOIN projects ON projects.id = floors.project_id
    WHERE locations.id = issues.location_id AND projects.owner_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "team full access" ON inventory_items;
CREATE POLICY "owner full access" ON inventory_items FOR ALL USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = inventory_items.project_id AND projects.owner_id = auth.uid())
);

DROP POLICY IF EXISTS "team full access" ON inventory_levels;
CREATE POLICY "owner full access" ON inventory_levels FOR ALL USING (
  EXISTS (
    SELECT 1 FROM inventory_items JOIN projects ON projects.id = inventory_items.project_id
    WHERE inventory_items.id = inventory_levels.item_id AND projects.owner_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "team full access" ON inventory_movements;
CREATE POLICY "owner full access" ON inventory_movements FOR ALL USING (
  EXISTS (
    SELECT 1 FROM inventory_items JOIN projects ON projects.id = inventory_items.project_id
    WHERE inventory_items.id = inventory_movements.item_id AND projects.owner_id = auth.uid()
  )
);

DROP POLICY IF EXISTS "team full access" ON notes;
CREATE POLICY "owner full access" ON notes FOR ALL USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = notes.project_id AND projects.owner_id = auth.uid())
);

DROP POLICY IF EXISTS "team full access" ON tasks;
CREATE POLICY "owner full access" ON tasks FOR ALL USING (
  EXISTS (SELECT 1 FROM projects WHERE projects.id = tasks.project_id AND projects.owner_id = auth.uid())
);

COMMIT;
*/
